
$(document).ready(function(){
		$('#left1').addClass('se-slope-black');
		$('#left2').addClass('se-slope-pink');
		$('#left3').addClass('se-slope-pink');
		$('#left4').addClass('se-slope-black');


	$('#hover1').html('<h3><a href="../doforum/">Go To Forum</a></h3> <p>People Who do The best they beleive if they do it together then best of the best can be happen . so we are about to introduce a place where you will make mistake together, you can share together , You can learn together , and the best thing is, you can do together !People Who do The best they beleive if they do it together then best of the best can be happen . so we are about to introduce a place where you will make mistake together, you can share together , You can learn together , and the best thing is, you can do together !People Who do The best they beleive if they do it together then best of the best can be happen . so we are about to introduce a place where you will make mistake together, you can share together , You can learn together , and the best thing is, you can do together !People Who do The best they beleive if they do it together then best of the best can be happen . so we are about to introduce a place where you will make mistake together, you can share together , You can learn together , and the best thing is, you can do together !</p>');
	$('#hover2').html('<h3><a href="../blog/">Read DoLovers Articles</a></h3><p>A multi-blogging Frame Where peoples share their experiences, researches, and more.. Read, comment and interact with , If you want to write for us with anything good , you are heartily welcome . Contact us anytime with your subject of writing. So start exploring now .A multi-blogging Frame Where peoples share their experiences, researches, and more.. Read, comment and interact with , If you want to write for us with anything good , you are heartily welcome . Contact us anytime with your subject of writing. So start exploring now .A multi-blogging Frame Where peoples share their experiences, researches, and more.. Read, comment and interact with , If you want to write for us with anything good , you are heartily welcome . Contact us anytime with your subject of writing. So start exploring now .A multi-blogging Frame Where peoples share their experiences, researches, and more.. Read, comment and interact with , If you want to write for us with anything good , you are heartily welcome . Contact us anytime with your subject of writing. So start exploring now .</p>');
	$('#hover3').html('<h3><a href="../studio/">Love Shortfilms ?</a></h3><p>A mind can think of anything , Some mind think beyond achievable. some mind undestimate their abilities . It is a shortfilm about the mind nature - negetive thinking habit - and fight back !A mind can think of anything , Some mind think beyond achievable. some mind undestimate their abilities . It is a shortfilm about the mind nature - negetive thinking habit - and fight back !A mind can think of anything , Some mind think beyond achievable. some mind undestimate their abilities . It is a shortfilm about the mind nature - negetive thinking habit - and fight back !A mind can think of anything , Some mind think beyond achievable. some mind undestimate their abilities . It is a shortfilm about the mind nature - negetive thinking habit - and fight back !</p>');
	$('#hover4').html('<h3><a href="../sagir/#contact">Need a Website ?</a></h3><p>Every time it is a delightful achievement when we get a message from you people. This site is fully created for you all. Read , Share , Learn. If you want to contribute anytime contact us !Every time it is a delightful achievement when we get a message from you people. This site is fully created for you all. Read , Share , Learn. If you want to contribute anytime contact us !Every time it is a delightful achievement when we get a message from you people. This site is fully created for you all. Read , Share , Learn. If you want to contribute anytime contact us !Every time it is a delightful achievement when we get a message from you people. This site is fully created for you all. Read , Share , Learn. If you want to contribute anytime contact us !</p>');
})

$('#left1').hover(function(){
		$('#left1').removeClass('se-slope-pink').addClass('se-slope-black');
		$('#left2').removeClass('se-slope-black').addClass('se-slope-pink');
		$('#left3').removeClass('se-slope-black').addClass('se-slope-pink');
		$('#left4').removeClass('se-slope-pink').addClass('se-slope-black');


	$('#hover1').html('<h3><a href="../doforum/">Go To Forum</a></h3>');
	$('#hover2').html('<h3><a href="../blog/">Read DoLovers Articles</a></h3><p>A multi-blogging Frame Where peoples share their experiences, researches, and more.. Read, comment and interact with , If you want to write for us with anything good , you are heartily welcome . Contact us anytime with your subject of writing. So start exploring now .A multi-blogging Frame Where peoples share their experiences, researches, and more.. Read, comment and interact with , If you want to write for us with anything good , you are heartily welcome . Contact us anytime with your subject of writing. So start exploring now .</p>');
	$('#hover3').html('<h3><a href="../studio/">Love Shortfilms ?</a></h3><p>A mind can think of anything , Some mind think beyond achievable. some mind undestimate their abilities . It is a shortfilm about the mind nature - negetive thinking habit - and fight back !A mind can think of anything , Some mind think beyond achievable. some mind undestimate their abilities . It is a shortfilm about the mind nature - negetive thinking habit - and fight back !A mind can think of anything , Some mind think beyond achievable. some mind undestimate their abilities . It is a shortfilm about the mind nature - negetive thinking habit - and fight back !A mind can think of anything , Some mind think beyond achievable. some mind undestimate their abilities . It is a shortfilm about the mind nature - negetive thinking habit - and fight back !</p>');
	$('#hover4').html('<h3><a href="../sagir/#contact">Need a Website ?</a></h3><p>Every time it is a delightful achievement when we get a message from you people. This site is fully created for you all. Read , Share , Learn. If you want to contribute anytime contact us !Every time it is a delightful achievement when we get a message from you people. This site is fully created for you all. Read , Share , Learn. If you want to contribute anytime contact us !Every time it is a delightful achievement when we get a message from you people. This site is fully created for you all. Read , Share , Learn. If you want to contribute anytime contact us !Every time it is a delightful achievement when we get a message from you people. This site is fully created for you all. Read , Share , Learn. If you want to contribute anytime contact us !</p>');
})   


$('#left2').hover(function(){
		$('#left1').removeClass('se-slope-black').addClass('se-slope-black');
		$('#left2').removeClass('se-slope-pink').addClass('se-slope-pink');
		$('#left3').removeClass('se-slope-black').addClass('se-slope-pink');
		$('#left4').removeClass('se-slope-pink').addClass('se-slope-black');

	$('#hover1').html('<h3><a href="../doforum/">Go To Forum</a></h3><p>People Who do The best they beleive if they do it together then best of the best can be happen . so we are about to introduce a place where you will make mistake together, you can share together , You can learn together , and the best thing is, you can do together !People Who do The best they beleive if they do it together then best of the best can be happen . so we are about to introduce a place where you will make mistake together, you can share together , You can learn together , and the best thing is, you can do together !.People Who do The best they beleive if they do it together then best of the best can be happen . so we are about to introduce a place where you will make mistake together, you can share together , You can learn together , and the best thing is, you can do together !</p>');
	$('#hover2').html('<h3><a href="../blog/">Read DoLovers Articles</a></h3>');
	$('#hover3').html('<h3><a href="../studio/">Love Shortfilms ?</a></h3><p>A mind can think of anything , Some mind think beyond achievable. some mind undestimate their abilities . It is a shortfilm about the mind nature - negetive thinking habit - and fight back !A mind can think of anything , Some mind think beyond achievable. some mind undestimate their abilities . It is a shortfilm about the mind nature - negetive thinking habit - and fight back !A mind can think of anything , Some mind think beyond achievable. some mind undestimate their abilities . It is a shortfilm about the mind nature - negetive thinking habit - and fight back !A mind can think of anything , Some mind think beyond achievable. some mind undestimate their abilities . It is a shortfilm about the mind nature - negetive thinking habit - and fight back !A mind can think of anything , Some mind think beyond achievable. some mind undestimate their abilities . It is a shortfilm about the mind nature - negetive thinking habit - and fight back !A mind can think of anything , Some mind think beyond achievable. some mind undestimate their abilities . It is a shortfilm about the mind nature - negetive thinking habit - and fight back !A mind can think of anything , Some mind think beyond achievable. some mind undestimate their abilities . It is a shortfilm about the mind nature - negetive thinking habit - and fight back !A mind can think of anything , Some mind think beyond achievable. some mind undestimate their abilities . It is a shortfilm about the mind nature - negetive thinking habit - and fight back !</p>');
	$('#hover4').html('<h3><a href="../sagir/#contact">Need a Website ?</a></h3><p>Every time it is a delightful achievement when we get a message from you people. This site is fully created for you all. Read , Share , Learn. If you want to contribute anytime contact us !Every time it is a delightful achievement when we get a message from you people. This site is fully created for you all. Read , Share , Learn. If you want to contribute anytime contact us !Every time it is a delightful achievement when we get a message from you people. This site is fully created for you all. Read , Share , Learn. If you want to contribute anytime contact us !Every time it is a delightful achievement when we get a message from you people. This site is fully created for you all. Read , Share , Learn. If you want to contribute anytime contact us !</p>');
})  

$('#left3').hover(function(){


		$('#left1').removeClass('se-slope-pink').addClass('se-slope-black');
		$('#left2').removeClass('se-slope-black').addClass('se-slope-pink');

		$('#left3').removeClass('se-slope-pink').addClass('se-slope-pink');
		$('#left4').removeClass('se-slope-black').addClass('se-slope-black');

	$('#hover1').html('<h3><a href="../doforum/">Go To Forum</a></h3><p>People Who do The best they beleive if they do it together then best of the best can be happen . so we are about to introduce a place where you will make mistake together, you can share together , You can learn together , and the best thing is, you can do together !People Who do The best they beleive if they do it together then best of the best can be happen . so we are about to introduce a place where you will make mistake together, you can share together , You can learn together , and the best thing is, you can do together !eople Who do The best they beleive if they do it together then best of the best can be happen . so we are about to introduce a place where you will make mistake together, you can share together , You can learn together , and the best thing is, you can do together !</p>');
	$('#hover2').html('<h3><a href="../blog/">Read DoLovers Articles</a></h3><p>A multi-blogging Frame Where peoples share their experiences, researches, and more.. Read, comment and interact with , If you want to write for us with anything good , you are heartily welcome . Contact us anytime with your subject of writing. So start exploring now. A multi-blogging Frame Where peoples share their experiences, researches, and more.. Read, comment and interact with , If you want to write for us with anything good , you are heartily welcome . Contact us anytime with your subject of writing. So start exploring now .</p>');
	$('#hover3').html('<h3><a href="../studio/">Love Shortfilms ?</a></h3>');
	$('#hover4').html('<h3><a href="../sagir/#contact">Need a Website ?</a></h3><p>Every time it is a delightful achievement when we get a message from you people. This site is fully created for you all. Read , Share , Learn. If you want to contribute anytime contact us !Every time it is a delightful achievement when we get a message from you people. This site is fully created for you all. Read , Share , Learn. If you want to contribute anytime contact us !Every time it is a delightful achievement when we get a message from you people. This site is fully created for you all. Read , Share , Learn. If you want to contribute anytime contact us !Every time it is a delightful achievement when we get a message from you people. This site is fully created for you all. Read , Share , Learn. If you want to contribute anytime contact us !</p>');
}) 

$('#left4').hover(function(){
$('#left1').removeClass('se-slope-pink').addClass('se-slope-black');
		$('#left2').removeClass('se-slope-black').addClass('se-slope-pink');
		$('#left3').removeClass('se-slope-black').addClass('se-slope-pink');
		$('#left4').removeClass('se-slope-pink').addClass('se-slope-black');
	$('#hover1').html('<h3><a href="../doforum/">Go To Forum</a></h3><p>People Who do The best they beleive if they do it together then best of the best can be happen . so we are about to introduce a place where you will make mistake together, you can share together , You can learn together , and the best thing is, you can do together !People Who do The best they beleive if they do it together then best of the best can be happen . so we are about to introduce a place where you will make mistake together, you can share together , You can learn together , and the best thing is, you can do together !People Who do The best they beleive if they do it together then best of the best can be happen . so we are about to introduce a place where you will make mistake together, you can share together , You can learn together , and the best thing is, you can do together !</p>');
	$('#hover2').html('<h3><a href="../blog/">Read DoLovers Articles</a></h3><p>A multi-blogging Frame Where peoples share their experiences, researches, and more.. Read, comment and interact with , If you want to write for us with anything good , you are heartily welcome . Contact us anytime with your subject of writing. So start exploring now .People Who do The best they beleive if they do it together then best of the best can be happen . so we are about to introduce a place where you will make mistake together, you can share together , You can learn together , and the best thing is, you can do together !!.</p>');
	$('#hover3').html('<h3><a href="../studio/">Love Shortfilms ?</a></h3><p>A mind can think of anything , Some mind think beyond achievable. some mind undestimate their abilities . It is a shortfilm about the mind nature - negetive thinking habit - and fight back !A mind can think of anything , Some mind think beyond achievable. some mind undestimate their abilities . It is a shortfilm about the mind nature - negetive thinking habit - and fight back !A mind can think of anything , Some mind think beyond achievable. some mind undestimate their abilities . It is a shortfilm about the mind nature - negetive thinking habit - and fight back !A mind can think of anything , Some mind think beyond achievable. some mind undestimate their abilities . It is a shortfilm about the mind nature - negetive thinking habit - and fight back !A mind can think of anything , Some mind think beyond achievable. some mind undestimate their abilities . It is a shortfilm about the mind nature - negetive thinking habit - and fight back !A mind can think of anything , Some mind think beyond achievable. some mind undestimate their abilities . It is a shortfilm about the mind nature - negetive thinking habit - and fight back !A mind can think of anything , Some mind think beyond achievable. some mind undestimate their abilities . It is a shortfilm about the mind nature - negetive thinking habit - and fight back !A mind can think of anything , Some mind think beyond achievable. some mind undestimate their abilities . It is a shortfilm about the mind nature - negetive thinking habit - and fight back !</p>');
	$('#hover4').html('<h3><a href="../sagir/#contact">Need a Website ?</a></h3>');
}) 